/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import irrgarten.Enumerados.Directions;
import javax.swing.JButton;

/**
 *
 * @author theki
 */
public class Cursors extends javax.swing.JDialog {

    private Directions direccion;
    /**
     * Creates new form Cursors
     */
    public Cursors(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonArriba = new javax.swing.JButton();
        botonDerecha = new javax.swing.JButton();
        botonAbajo = new javax.swing.JButton();
        botonIzquierdo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        botonArriba.setText("Arriba");
        botonArriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArribaActionPerformed(evt);
            }
        });

        botonDerecha.setText("Derecha");
        botonDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDerechaActionPerformed(evt);
            }
        });

        botonAbajo.setText("Abajo");
        botonAbajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAbajoActionPerformed(evt);
            }
        });

        botonIzquierdo.setText("Izquierda");
        botonIzquierdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIzquierdoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(botonIzquierdo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(botonDerecha)
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonAbajo)
                    .addComponent(botonArriba))
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(botonArriba)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonIzquierdo)
                    .addComponent(botonDerecha))
                .addGap(18, 18, 18)
                .addComponent(botonAbajo)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAbajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAbajoActionPerformed
        direccion = Directions.DOWN;
        dispose();
    }//GEN-LAST:event_botonAbajoActionPerformed

    private void botonDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDerechaActionPerformed
        direccion = Directions.RIGHT;
        dispose();
    }//GEN-LAST:event_botonDerechaActionPerformed

    private void botonArribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArribaActionPerformed
        direccion = Directions.UP;
        dispose();
    }//GEN-LAST:event_botonArribaActionPerformed

    private void botonIzquierdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIzquierdoActionPerformed
        direccion = Directions.LEFT;
        dispose();
    }//GEN-LAST:event_botonIzquierdoActionPerformed

    public JButton getBotonAbajo() {
        return botonAbajo;
    }

    public void setBotonAbajo(JButton botonAbajo) {
        this.botonAbajo = botonAbajo;
    }

    public JButton getBotonArriba() {
        return botonArriba;
    }

    public void setBotonArriba(JButton botonArriba) {
        this.botonArriba = botonArriba;
    }

    public JButton getBotonDerecha() {
        return botonDerecha;
    }

    public void setBotonDerecha(JButton botonDerecha) {
        this.botonDerecha = botonDerecha;
    }

    public JButton getBotonIzquierdo() {
        return botonIzquierdo;
    }

    public void setBotonIzquierdo(JButton botonIzquierdo) {
        this.botonIzquierdo = botonIzquierdo;
    }

    
    
    Directions getDirection(){
        
        setVisible(true);
        
        
        return direccion;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAbajo;
    private javax.swing.JButton botonArriba;
    private javax.swing.JButton botonDerecha;
    private javax.swing.JButton botonIzquierdo;
    // End of variables declaration//GEN-END:variables
}
